### ISSUE TITLE
May I ask about colab pro?

### ISSUE THREAD

**Issue by thanisornsr** [forever208/YOLOv4_Traffic_Cones#1]
Sorry that this issue is not about this repo but I don't know how to contact you. I want to upgrade my colab to colab pro in order to work on my thesis. I saw that you use Swedish mobile number and success on doing it. Would you mind suggesting me how to do it?

Thanks,
Than

**Comment by forever208** [comment]
@thanisornsr  hi Than, I solved this issue by registering a new google account (it doesn't matter which country your phone number belongs to), e.g. my phone number is Swedish

Then I used a VPN with an American IP, and the purchase of Colab pro succeeded
(But I am not sure if it is necessary to use a VPN to make a payment)

**Comment by thanisornsr** [comment]
Is this new google account information have to be in USA? Because I am also living in Sweden. And how about the payment? Do I need American card or use just Swedish debit card?

**Comment by forever208** [comment]
@thanisornsr  you don't have to register with the USA info, but you have to use a USA postcode to make a payment. 
the payment is on dollars, I paid it by credit card.

**Comment by thanisornsr** [comment]
Thank you for your kindly reply.
